'use strict';
/* 노드 그래프 이펙트 렌더러 (pxf.graph@1 호환) — 브라우저/Node 공용.
 * 형식·노드 의미는 용사주식회사 PXF 공방의 공개 계약서를 참고했다(출처·방침은 SIDE.md 참조). 구현은 이 저장소에서 새로 작성.
 * 그래프 = settings{size,frames,fps,loop} + nodes[{id,type,params}] + links[{f,t,p}]. 파라미터는 상수 또는 키프레임 {k:[[프레임,값,이징]..]} 또는 구간 {a,b,e,t0,t1}.
 * 레이어는 두 종류: 'i' 강도 맵(1채널 0~1)과 'c' 색(RGBA, 비곱셈). Palette 가 강도 → 색으로 바꾼다.
 * 지원: Shape Noise Gradient Particles Lightning Arc Stroke Spike Checker Grid / Transform Repeat Echo Blur Glow Levels Dither Displace Polar Pixelate
 *       Blend Mask Palette Tint Outline Quantize Output. (AuraShell·Revolve 는 미지원 — 빈 레이어로 대체하고 경고)
 * 사용: FXGraph.render(graph) → { size, frames, fps, loop, data:[Uint8ClampedArray(RGBA)...], warnings:[] } */
(function (root) {
  const clamp = (v, a, b) => v < a ? a : v > b ? b : v, lerp = (a, b, t) => a + (b - a) * t, TAU = Math.PI * 2, DEG = Math.PI / 180;
  const EASE = { linear: t => t, in: t => t * t, out: t => 1 - (1 - t) * (1 - t), inout: t => t < .5 ? 2 * t * t : 1 - 2 * (1 - t) * (1 - t), in3: t => t * t * t, out3: t => 1 - Math.pow(1 - t, 3), pulse: t => Math.sin(Math.PI * t), wave: t => .5 - .5 * Math.cos(TAU * t), step: t => t >= 1 ? 1 : 0 };
  const rng = seed => { let a = (seed >>> 0) + 0x6D2B79F5; return () => { a = (a + 0x6D2B79F5) >>> 0; let t = a; t = Math.imul(t ^ t >>> 15, t | 1); t ^= t + Math.imul(t ^ t >>> 7, t | 61); return ((t ^ t >>> 14) >>> 0) / 4294967296; }; };
  const hash2 = (x, y, s) => { let h = (Math.imul(x | 0, 374761393) + Math.imul(y | 0, 668265263) + Math.imul(s | 0, 1274126177)) | 0; h = Math.imul(h ^ h >>> 13, 1274126177); return ((h ^ h >>> 16) >>> 0) / 4294967296; };

  /* ---------- 파라미터 ---------- */
  function pv(raw, def, f, tN) {
    if (raw === undefined) return def;
    if (raw && typeof raw === 'object' && !Array.isArray(raw)) {
      if (Array.isArray(raw.k) && raw.k.length) { const k = raw.k; if (f <= k[0][0]) return k[0][1]; for (let i = 0; i < k.length - 1; i++) { const a = k[i], b = k[i + 1]; if (f < b[0]) return lerp(a[1], b[1], (EASE[a[2]] || EASE.linear)((f - a[0]) / (b[0] - a[0]))); } return k[k.length - 1][1]; }
      if ('a' in raw) { const t0 = raw.t0 || 0, t1 = raw.t1 === undefined ? 1 : raw.t1, u = t1 > t0 ? clamp((tN - t0) / (t1 - t0), 0, 1) : (tN >= t1 ? 1 : 0); return lerp(raw.a, raw.b, (EASE[raw.e] || EASE.linear)(u)); }
    }
    return raw;
  }

  /* ---------- 레이어 ---------- */
  const newI = N => ({ t: 'i', w: N, h: N, d: new Float32Array(N * N) }), newC = N => ({ t: 'c', w: N, h: N, d: new Float32Array(N * N * 4) });
  const toC = L => { if (L.t === 'c') return L; const o = newC(L.w); for (let i = 0; i < L.d.length; i++) { o.d[i * 4] = o.d[i * 4 + 1] = o.d[i * 4 + 2] = 1; o.d[i * 4 + 3] = L.d[i]; } return o; };
  const toI = L => { if (L.t === 'i') return L; const o = newI(L.w); for (let i = 0; i < o.d.length; i++) o.d[i] = L.d[i * 4 + 3]; return o; };
  const lumaOf = (r, g, b) => .299 * r + .587 * g + .114 * b;
  function sampleI(L, x, y) { const fx = x - .5, fy = y - .5, x0 = Math.floor(fx), y0 = Math.floor(fy), tx = fx - x0, ty = fy - y0, w = L.w, h = L.h, d = L.d; const g = (a, b) => (a < 0 || b < 0 || a >= w || b >= h) ? 0 : d[b * w + a]; return lerp(lerp(g(x0, y0), g(x0 + 1, y0), tx), lerp(g(x0, y0 + 1), g(x0 + 1, y0 + 1), tx), ty); }
  function sampleC(L, x, y, out) { const fx = x - .5, fy = y - .5, x0 = Math.floor(fx), y0 = Math.floor(fy), tx = fx - x0, ty = fy - y0, w = L.w, h = L.h, d = L.d; out[0] = out[1] = out[2] = out[3] = 0; const add = (a, b, wt) => { if (a < 0 || b < 0 || a >= w || b >= h || wt <= 0) return; const i = (b * w + a) * 4, al = d[i + 3] * wt; out[0] += d[i] * al; out[1] += d[i + 1] * al; out[2] += d[i + 2] * al; out[3] += al; }; add(x0, y0, (1 - tx) * (1 - ty)); add(x0 + 1, y0, tx * (1 - ty)); add(x0, y0 + 1, (1 - tx) * ty); add(x0 + 1, y0 + 1, tx * ty); }
  function warp(L, map) { /* map(px,py,o) → o=[sx,sy] 또는 false */ const N = L.w, o = L.t === 'i' ? newI(N) : newC(N), s = [0, 0], tmp = [0, 0, 0, 0]; for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) { if (map(x + .5, y + .5, s) === false) continue; if (L.t === 'i') o.d[y * N + x] = sampleI(L, s[0], s[1]); else { sampleC(L, s[0], s[1], tmp); const a = tmp[3], i = (y * N + x) * 4; if (a > 1e-6) { o.d[i] = tmp[0] / a; o.d[i + 1] = tmp[1] / a; o.d[i + 2] = tmp[2] / a; o.d[i + 3] = a; } } } return o; }
  function hexRgb(h) { const n = parseInt(String(h).replace('#', '').padEnd(6, '0').slice(0, 6), 16); return [(n >> 16 & 255) / 255, (n >> 8 & 255) / 255, (n & 255) / 255]; }
  const empty = (N) => newI(N);
  const dist2seg = (px, py, ax, ay, bx, by) => { const dx = bx - ax, dy = by - ay, l2 = dx * dx + dy * dy, t = l2 > 0 ? clamp(((px - ax) * dx + (py - ay) * dy) / l2, 0, 1) : 0, qx = ax + dx * t, qy = ay + dy * t; return [Math.hypot(px - qx, py - qy), t]; };
  function drawSeg(L, ax, ay, bx, by, wpx, val) { /* 두께 wpx 선분을 강도 val 로 max 합성 */ const N = L.w, r = wpx / 2 + 1, x0 = Math.max(0, Math.floor(Math.min(ax, bx) - r)), x1 = Math.min(N - 1, Math.ceil(Math.max(ax, bx) + r)), y0 = Math.max(0, Math.floor(Math.min(ay, by) - r)), y1 = Math.min(N - 1, Math.ceil(Math.max(ay, by) + r)); for (let y = y0; y <= y1; y++) for (let x = x0; x <= x1; x++) { const dd = dist2seg(x + .5, y + .5, ax, ay, bx, by)[0], a = clamp(.5 + wpx / 2 - dd, 0, 1) * val; if (a > L.d[y * N + x]) L.d[y * N + x] = a; } }
  function blurLayer(L, radius, passes) { if (radius <= 0) return L; const N = L.w, ch = L.t === 'i' ? 1 : 4; let src = new Float32Array(L.d); const pre = ch === 4; if (pre) for (let i = 0; i < N * N; i++) { const a = src[i * 4 + 3]; src[i * 4] *= a; src[i * 4 + 1] *= a; src[i * 4 + 2] *= a; } for (let p = 0; p < passes; p++) for (let dir = 0; dir < 2; dir++) { const dst = new Float32Array(src.length), n = radius * 2 + 1; for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) for (let c = 0; c < ch; c++) { let s = 0; for (let k = -radius; k <= radius; k++) { const xx = dir ? x : x + k, yy = dir ? y + k : y; if (xx < 0 || yy < 0 || xx >= N || yy >= N) continue; s += src[(yy * N + xx) * ch + c]; } dst[(y * N + x) * ch + c] = s / n; } src = dst; } const o = ch === 1 ? newI(N) : newC(N); if (pre) for (let i = 0; i < N * N; i++) { const a = src[i * 4 + 3]; o.d[i * 4 + 3] = a; if (a > 1e-6) { o.d[i * 4] = src[i * 4] / a; o.d[i * 4 + 1] = src[i * 4 + 1] / a; o.d[i * 4 + 2] = src[i * 4 + 2] / a; } } else o.d.set(src); return o; }

  /* ---------- 노이즈 ---------- */
  function vnoise(x, y, sx, sy, seed) { const x0 = Math.floor(x), y0 = Math.floor(y), tx = x - x0, ty = y - y0, ux = tx * tx * (3 - 2 * tx), uy = ty * ty * (3 - 2 * ty), m = (a, p) => ((a % p) + p) % p, h = (a, b) => hash2(m(a, sx), m(b, sy), seed); return lerp(lerp(h(x0, y0), h(x0 + 1, y0), ux), lerp(h(x0, y0 + 1), h(x0 + 1, y0 + 1), ux), uy); }
  function cells(x, y, sx, sy, seed) { const x0 = Math.floor(x), y0 = Math.floor(y); let best = 9; for (let j = -1; j <= 1; j++) for (let i = -1; i <= 1; i++) { const cx = x0 + i, cy = y0 + j, wx = ((cx % sx) + sx) % sx, wy = ((cy % sy) + sy) % sy, px = cx + hash2(wx, wy, seed), py = cy + hash2(wx, wy, seed + 77); best = Math.min(best, Math.hypot(x - px, y - py)); } return clamp(best, 0, 1); }

  /* ---------- 도형 ---------- */
  function shapeSdf(shape, x, y, R, s2, pts, K0) {
    const r = Math.hypot(x, y);
    switch (shape) {
      case 'ring': { const th = Math.max(.5 * K0, R * s2); return Math.abs(r - (R - th / 2)) - th / 2; }
      case 'square': return Math.max(Math.abs(x), Math.abs(y)) - R;
      case 'diamond': return Math.abs(x) + Math.abs(y) - R;
      case 'polygon': { const n = Math.max(3, pts), a = Math.atan2(y, x), seg = TAU / n, k = Math.floor(a / seg + .5) * seg; return Math.cos(a - k) * r - R * Math.cos(Math.PI / n); }
      case 'star': { const n = Math.max(2, pts), a = Math.atan2(y, x) + Math.PI / 2, seg = TAU / n, u = ((a % seg) + seg) % seg / seg, k = u < .5 ? u * 2 : (1 - u) * 2, rb = lerp(R * s2, R, 1 - k); return r - rb; }
      case 'shard': { const w = Math.max(.5 * K0, R * s2); return (Math.abs(x) / w + Math.abs(y) / R - 1) * w; }
      case 'crescent': return Math.max(r - R, -(Math.hypot(x - R * s2, y) - R * .85));
      case 'cross': { const w = Math.max(.5 * K0, R * s2) / 2; return Math.min(Math.max(Math.abs(x) - R, Math.abs(y) - w), Math.max(Math.abs(y) - R, Math.abs(x) - w)); }
      default: return r - R;
    }
  }

  /* 해상도 배율 k: 그래프는 settings.size 기준(px)으로 설계되므로, 더 촘촘하게 그릴 때 길이(px) 단위 파라미터에 k 를 곱한다. 정수형은 반올림 */
  const PX = { Shape: ['size', 'stroke'], Arc: ['radius', 'thick'], Gradient: ['radius'], Particles: ['aw', 'ah', 'speed', 'sizeA', 'sizeB', 'turb', 'ground', 'gravity'], Lightning: ['thick'], Spike: ['width'], Checker: ['size', 'ox', 'oy'], Grid: ['cellW', 'cellH', 'gap', 'ox', 'oy'], Stroke: ['width'], Transform: ['tx', 'ty'], Repeat: ['dx', 'dy'], Blur: ['radius'], Glow: ['radius'], Outline: ['width'], Displace: ['amount'], Polar: ['rIn', 'rOut'], Pixelate: ['block'] };
  const PXINT = { Lightning: ['thick'], Blur: ['radius'], Glow: ['radius'], Outline: ['width'], Pixelate: ['block'] };

  /* ---------- 노드 구현 ---------- */
  const NODES = {};
  NODES.Shape = (n, c) => {
    const N = c.N, o = newI(N), P = c.P, shape = P('shape', 'circle'), cx = P('x', .5) * N, cy = P('y', .5) * N, R = P('size', 12), s2 = P('size2', .4), pts = Math.round(P('points', 5)), rot = P('rot', 0) * DEG, asp = Math.max(.05, P('aspect', 1)), stroke = P('stroke', 0), fall = P('falloff', 0), inten = P('intensity', 1), cs = Math.cos(-rot), sn = Math.sin(-rot);
    for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) { const dx = x + .5 - cx, dy = y + .5 - cy, rx = dx * cs - dy * sn, ry = (dx * sn + dy * cs) / asp; let d = shapeSdf(shape, rx, ry, R, s2, pts, c.k); if (stroke > 0) d = Math.abs(d) - stroke / 2; let v = clamp(.5 - d, 0, 1); if (fall > 0 && R > 0) v *= 1 - fall * clamp(Math.hypot(rx, ry) / R, 0, 1); o.d[y * N + x] = v * inten; } return o;
  };
  NODES.Arc = (n, c) => {
    const N = c.N, o = newI(N), P = c.P, cx = P('x', .5) * N, cy = P('y', .5) * N, R = P('radius', 22), th = P('thick', 8), start = P('start', -150) * DEG, sweep = P('sweep', 220) * DEG, head = P('head', 1), tail = Math.max(.01, P('tail', .7)), taper = P('taper', 1.2), asp = Math.max(.05, P('aspect', 1)), rot = P('rot', 0) * DEG, inten = P('intensity', 1), cs = Math.cos(-rot), sn = Math.sin(-rot);
    for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) { const dx = x + .5 - cx, dy = y + .5 - cy, rx = dx * cs - dy * sn, ry = (dx * sn + dy * cs) / asp, r = Math.hypot(rx, ry); const th0 = Math.atan2(ry, rx), dth = sweep >= 0 ? ((th0 - start) % TAU + TAU) % TAU : ((start - th0) % TAU + TAU) % TAU, u = dth / (Math.abs(sweep) || 1e-6); if (u > 1) continue; /* 지정한 호 범위 밖은 그리지 않는다 */ const s = (head - u) / tail; if (s < 0 || s > 1) continue; const w = th * Math.pow(1 - s, taper) + .001, v = clamp(.5 + w / 2 - Math.abs(r - R), 0, 1) * (1 - s * .6); o.d[y * N + x] = v * inten; } return o;
  };
  NODES.Noise = (n, c) => {
    const N = c.N, o = newI(N), P = c.P, type = P('type', 'fbm'), sx = Math.max(1, Math.round(P('scaleX', 4))), sy = Math.max(1, Math.round(P('scaleY', 4))), oct = Math.round(P('octaves', 3)), seed = Math.round(P('seed', 1)), scx = P('scrollX', 0) * c.tl, scy = P('scrollY', 0) * c.tl, con = P('contrast', 1), bias = P('bias', 0);
    for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) { let v = 0, a = 1, tot = 0; for (let k = 0; k < oct; k++) { const f = 1 << k, u = ((x + .5) / N + scx) * sx * f, w = ((y + .5) / N + scy) * sy * f, px = sx * f, py = sy * f; let nv = type === 'cells' ? cells(u, w, px, py, seed + k * 31) : vnoise(u, w, px, py, seed + k * 31); if (type === 'ridged') nv = 1 - Math.abs(nv * 2 - 1); v += nv * a; tot += a; a *= .5; } v = v / tot; o.d[y * N + x] = clamp((v - .5) * con + .5 + bias, 0, 1); } return o;
  };
  NODES.Gradient = (n, c) => {
    const N = c.N, o = newI(N), P = c.P, type = P('type', 'linear'), cx = P('x', .5) * N, cy = P('y', .5) * N, ang = P('angle', 90) * DEG, R = Math.max(1, P('radius', 24)), off = P('offset', 0), rep = P('repeat', false), inv = P('invert', false), asp = Math.max(.05, P('aspect', 1)), dx0 = Math.cos(ang), dy0 = Math.sin(ang);
    for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) { const dx = x + .5 - cx, dy = (y + .5 - cy) / asp; let v; if (type === 'radial') v = Math.hypot(dx, dy) / R; else if (type === 'diamond') v = (Math.abs(dx) + Math.abs(dy)) / R; else if (type === 'angular') v = Math.atan2(dy, dx) / TAU + .5; else v = (dx * dx0 + dy * dy0) / (R * 2) + .5; v += off; v = rep ? v - Math.floor(v) : clamp(v, 0, 1); if (inv) v = 1 - v; o.d[y * N + x] = v; } return o;
  };
  NODES.Particles = (n, c) => {
    const N = c.N, o = newI(N), P = c.P, count = Math.round(P('count', 30)), seed = Math.round(P('seed', 1)), emit = P('emit', 'burst'), start = P('start', 0), span = P('span', 1), life = P('life', .5), lifeVar = P('lifeVar', .3), area = P('area', 'point'), ex = P('x', .5) * N, ey = P('y', .5) * N, aw = P('aw', 8), ah = P('ah', 8), dirMode = P('dirMode', 'fixed'), angle = P('angle', -90) * DEG, spread = P('spread', 360) * DEG, speed = P('speed', 1), speedVar = P('speedVar', .5), grav = P('gravity', 0), drag = P('drag', 0), turb = P('turb', 0), sizeA = P('sizeA', 2), sizeB = P('sizeB', 1), pshape = P('pshape', 'square'), stretch = P('stretch', 1), fade = P('fade', 'out'), bright = P('bright', 1), loop = P('loop', false), ground = P('ground', 0), bounce = P('bounce', .35), brightVar = P('brightVar', 0), t = c.loop ? c.tl : c.t, F = c.frames;
    for (let i = 0; i < count; i++) {
      const r = rng(seed * 9973 + i * 7919 + 13), te = emit === 'burst' ? start : start + r() * span, lf = Math.max(.02, life * (1 + (r() * 2 - 1) * lifeVar)); let age = (t - te) / lf; if (loop) { age = ((t - te) % 1 + 1) % 1 / lf; } if (age < 0 || age >= 1) { for (let q = 0; q < 8; q++) r(); continue; }
      let px = ex, py = ey; const ra = r(), rb = r(); if (area === 'circle') { const rr = Math.sqrt(ra) * aw / 2, th = rb * TAU; px += Math.cos(th) * rr; py += Math.sin(th) * rr; } else if (area === 'ring') { const th = ra * TAU; px += Math.cos(th) * aw / 2; py += Math.sin(th) * aw / 2; } else if (area === 'box') { px += (ra - .5) * aw; py += (rb - .5) * ah; } else if (area === 'line') { px += (ra - .5) * aw; }
      let base = angle; if (dirMode === 'outward') base = Math.atan2(py - ey, px - ex) || r() * TAU; else if (dirMode === 'inward') base = Math.atan2(ey - py, ex - px) || r() * TAU; const dir = base + (r() - .5) * spread, spd = speed * (1 + (r() * 2 - 1) * speedVar), bv = clamp(bright * (1 + (r() * 2 - 1) * brightVar), 0, 1), ph = r() * TAU, fa = age * lf * F;
      const dd = drag > 0 ? (1 - Math.pow(1 - drag, fa)) / drag : fa; let x = px + Math.cos(dir) * spd * dd, y = py + Math.sin(dir) * spd * dd + .5 * grav * fa * fa; if (turb > 0) { x += Math.sin(fa * .6 + ph) * turb; y += Math.cos(fa * .5 + ph) * turb * .6; } if (ground > 0 && y > ground) y = ground - (y - ground) * bounce;
      let a = fade === 'inout' ? Math.sin(Math.PI * age) : fade === 'flat' ? 1 : fade === 'flicker' ? ((hash2(i, Math.floor(c.f), seed) > .4) ? 1 : .35) * (1 - age) : 1 - age; a *= bv; const sz = Math.max(.3 * c.k, lerp(sizeA, sizeB, age)), half = sz / 2, rad = Math.ceil(half * Math.max(1, stretch) + 2), vdx = Math.cos(dir), vdy = Math.sin(dir);
      for (let yy = Math.max(0, Math.floor(y - rad)); yy <= Math.min(N - 1, Math.ceil(y + rad)); yy++) for (let xx = Math.max(0, Math.floor(x - rad)); xx <= Math.min(N - 1, Math.ceil(x + rad)); xx++) { const dx = xx + .5 - x, dy = yy + .5 - y; let d; if (pshape === 'diamond') d = Math.abs(dx) + Math.abs(dy) - half * 1.2; else if (pshape === 'circle') d = Math.hypot(dx, dy) - half; else if (pshape === 'plus') d = Math.min(Math.max(Math.abs(dx) - half * 1.2, Math.abs(dy) - half * .35), Math.max(Math.abs(dy) - half * 1.2, Math.abs(dx) - half * .35)); else if (pshape === 'dot') d = Math.max(Math.abs(dx), Math.abs(dy)) - .5 * c.k; else if (pshape === 'streak') { const along = dx * vdx + dy * vdy, perp = -dx * vdy + dy * vdx; d = Math.max(Math.abs(along) - half * Math.max(1, stretch) * 1.5, Math.abs(perp) - Math.max(.5 * c.k, half * .5)); } else d = Math.max(Math.abs(dx), Math.abs(dy)) - half; const v = clamp(.5 - d, 0, 1) * a; if (v > o.d[yy * N + xx]) o.d[yy * N + xx] = v; }
    } return o;
  };
  NODES.Lightning = (n, c) => {
    const N = c.N, o = newI(N), P = c.P, x0 = P('x0', .5) * N, y0 = P('y0', .05) * N, x1 = P('x1', .5) * N, y1 = P('y1', .95) * N, detail = Math.round(P('detail', 5)), jag = P('jag', .35), branch = P('branch', .25), blen = P('branchLen', .35), seed = Math.round(P('seed', 3)), rate = Math.round(P('rate', 2)), thick = Math.max(1, Math.round(P('thick', 1))), grow = P('grow', 1), inten = P('intensity', 1), r = rng(seed * 131 + (rate > 0 ? Math.floor(c.f / rate) : 0) * 977);
    const bolt = (ax, ay, bx, by, depth, j) => { let pts = [[ax, ay], [bx, by]]; for (let d = 0; d < depth; d++) { const np = [pts[0]]; for (let i = 0; i < pts.length - 1; i++) { const [px, py] = pts[i], [qx, qy] = pts[i + 1], mx = (px + qx) / 2, my = (py + qy) / 2, len = Math.hypot(qx - px, qy - py), nx = -(qy - py) / (len || 1), ny = (qx - px) / (len || 1), off = (r() * 2 - 1) * len * j * .5; np.push([mx + nx * off, my + ny * off], pts[i + 1]); } pts = np; } return pts; };
    const main = bolt(x0, y0, x1, y1, detail, jag), segs = []; for (let i = 0; i < main.length - 1; i++) segs.push([main[i], main[i + 1], 1]);
    const total = segs.length; for (let i = 1; i < main.length - 1; i++) if (r() < branch) { const [px, py] = main[i], ang = Math.atan2(y1 - y0, x1 - x0) + (r() < .5 ? -1 : 1) * (.4 + r() * .6), L = Math.hypot(x1 - x0, y1 - y0) * blen * (.4 + r() * .6), bp = bolt(px, py, px + Math.cos(ang) * L, py + Math.sin(ang) * L, Math.max(1, detail - 2), jag); for (let k = 0; k < bp.length - 1; k++) segs.push([bp[k], bp[k + 1], .7, i]); }
    const lim = grow * total; /* 가지는 뿌리가 자란 뒤에 나타난다 */
    let si = 0; for (const s of segs) { const mainIdx = s[3] === undefined ? si : s[3]; if (s[3] === undefined) si++; if (mainIdx < lim) drawSeg(o, s[0][0], s[0][1], s[1][0], s[1][1], thick, s[2] * inten); } return o;
  };
  NODES.Stroke = (n, c) => {
    const N = c.N, o = newI(N), P = c.P, pt = i => [P('x' + i, [.2, .4, .6, .8][i]) * N, P('y' + i, [.5, .3, .7, .5][i]) * N], p0 = pt(0), p1 = pt(1), p2 = pt(2), p3 = pt(3), width = P('width', 2), taper = P('taper', 1), from = P('from', 0), to = P('to', 1), span = P('span', true), vA = P('vA', .6), vM = P('vM', 1), vB = P('vB', .3), inten = P('intensity', 1), steps = 48;
    const bez = t => { const u = 1 - t; return [u * u * u * p0[0] + 3 * u * u * t * p1[0] + 3 * u * t * t * p2[0] + t * t * t * p3[0], u * u * u * p0[1] + 3 * u * u * t * p1[1] + 3 * u * t * t * p2[1] + t * t * t * p3[1]]; };
    let prev = null; for (let i = 0; i <= steps; i++) { const t = lerp(from, to, i / steps), q = bez(t), uu = span ? i / steps : t, wk = lerp(1, 4 * uu * (1 - uu), taper), v = (uu < .5 ? lerp(vA, vM, uu * 2) : lerp(vM, vB, (uu - .5) * 2)) * inten; if (prev) drawSeg(o, prev[0], prev[1], q[0], q[1], Math.max(.5 * c.k, width * wk), v); prev = q; } return o;
  };
  NODES.Spike = (n, c) => {
    const N = c.N, o = newI(N), P = c.P, bx = P('x0', .4) * N, by = P('y0', .85) * N, tx0 = P('x1', .6) * N, ty0 = P('y1', .15) * N, w = P('width', 10), taper = P('taper', 1), grow = P('grow', 1), base = P('base', .45), tip = P('tip', .8), facet = P('facet', .22), ridge = P('ridge', .12), shine = P('shine', -1), shineW = P('shineW', .1), inten = P('intensity', 1), tp = P('taperPow', 1), shineAmp = P('shineAmp', .6), tx = bx + (tx0 - bx) * grow, ty = by + (ty0 - by) * grow, ax = tx - bx, ay = ty - by, L = Math.hypot(ax, ay) || 1, ux = ax / L, uy = ay / L;
    for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) { const dx = x + .5 - bx, dy = y + .5 - by, u = (dx * ux + dy * uy) / L, lat = -dx * uy + dy * ux; if (u < 0 || u > 1) continue; const hw = w / 2 * Math.pow(1 - u * taper, tp); if (hw <= 0) continue; const cov = clamp(.5 + hw - Math.abs(lat), 0, 1); if (cov <= 0) continue; let v = lerp(base, tip, u); v *= 1 + (lat < 0 ? facet : -facet); if (Math.abs(lat) < .75) v += ridge; if (shine >= 0 && Math.abs(u - shine) < shineW) v += shineAmp * (1 - Math.abs(u - shine) / shineW); o.d[y * N + x] = clamp(v, 0, 1) * cov * inten; } return o;
  };
  NODES.Checker = (n, c) => {
    const N = c.N, o = newI(N), P = c.P, s = Math.max(1, P('size', 8)), iso = P('iso', false), ox = P('ox', 0), oy = P('oy', 0), a = P('a', 1), b = P('b', 0), pat = P('pattern', 'checker'), dot = P('dot', .35);
    for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) { const X = x + .5 - ox, Y = y + .5 - oy; let u, v, fu, fv; if (iso) { const p = X / s + Y / (s * .5), q = X / s - Y / (s * .5); u = Math.floor(p / 2); v = Math.floor(q / 2); fu = p / 2 - u - .5; fv = q / 2 - v - .5; } else { u = Math.floor(X / s); v = Math.floor(Y / s); fu = X / s - u - .5; fv = Y / s - v - .5; } o.d[y * N + x] = pat === 'dots' ? (Math.hypot(fu, fv) < dot ? a : b) : (((u + v) & 1) ? b : a); } return o;
  };
  NODES.Grid = (n, c) => {
    const N = c.N, o = newI(N), P = c.P, cw = Math.max(1, P('cellW', 8)), ch = Math.max(1, P('cellH', 8)), gap = P('gap', 1), ox = P('ox', 0), oy = P('oy', 0), lo = P('lo', .3), hi = P('hi', 1), gv = P('gapV', .1), seed = Math.round(P('seed', 1));
    for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) { const X = x + .5 - ox, Y = y + .5 - oy, u = Math.floor(X / cw), v = Math.floor(Y / ch), fx = X - u * cw, fy = Y - v * ch; o.d[y * N + x] = (fx < gap || fy < gap) ? gv : lerp(lo, hi, hash2(u, v, seed)); } return o;
  };
  NODES.Transform = (n, c, I) => {
    const L = I(0); if (!L) return empty(c.N); const P = c.P, N = c.N, tx = P('tx', 0), ty = P('ty', 0), sx = P('sx', 1) || .0001, sy = P('sy', 1) || .0001, rot = P('rot', 0) * DEG, pxp = P('px', .5) * N, pyp = P('py', .5) * N, cs = Math.cos(-rot), sn = Math.sin(-rot);
    return warp(L, (x, y, s) => { const dx = x - pxp - tx, dy = y - pyp - ty, rx = dx * cs - dy * sn, ry = dx * sn + dy * cs; s[0] = pxp + rx / sx; s[1] = pyp + ry / sy; });
  };
  function combine(A, B, mode, op) { /* A 아래, B 위. 둘 다 같은 종류가 되게 맞춘다 */ const N = (A || B).w; if (!A) A = B.t === 'i' ? newI(N) : newC(N); if (!B) B = A.t === 'i' ? newI(N) : newC(N); if (A.t === 'i' && B.t === 'i') { const o = newI(N); for (let i = 0; i < o.d.length; i++) { const a = A.d[i], b = B.d[i] * op; o.d[i] = clamp(mode === 'add' ? a + b : mode === 'screen' ? 1 - (1 - a) * (1 - b) : mode === 'max' ? Math.max(a, b) : mode === 'multiply' ? a * (1 - op + op * B.d[i]) : mode === 'subtract' ? a - b : b + a * (1 - b), 0, 1); } return o; }
    A = toC(A); B = toC(B); const o = newC(N); for (let i = 0; i < N * N; i++) { const j = i * 4, aa = A.d[j + 3], ba = B.d[j + 3] * op; let a, r, g, b; if (mode === 'add' || mode === 'screen' || mode === 'max' || mode === 'subtract') { const f = mode === 'subtract' ? -1 : 1; a = clamp(mode === 'max' ? Math.max(aa, ba) : mode === 'screen' ? 1 - (1 - aa) * (1 - ba) : aa + f * ba, 0, 1); const pr = k => { const x = A.d[j + k] * aa, y = B.d[j + k] * ba; return mode === 'max' ? (aa >= ba ? x : y) : mode === 'screen' ? x + y - x * y : x + f * y; }; r = pr(0); g = pr(1); b = pr(2); } else if (mode === 'multiply') { a = aa; r = A.d[j] * aa * (1 - op + op * B.d[j]); g = A.d[j + 1] * aa * (1 - op + op * B.d[j + 1]); b = A.d[j + 2] * aa * (1 - op + op * B.d[j + 2]); } else { a = ba + aa * (1 - ba); r = B.d[j] * ba + A.d[j] * aa * (1 - ba); g = B.d[j + 1] * ba + A.d[j + 1] * aa * (1 - ba); b = B.d[j + 2] * ba + A.d[j + 2] * aa * (1 - ba); } if (a > 1e-6) { o.d[j] = clamp(r / a, 0, 1); o.d[j + 1] = clamp(g / a, 0, 1); o.d[j + 2] = clamp(b / a, 0, 1); o.d[j + 3] = clamp(a, 0, 1); } } return o; }
  NODES.Blend = (n, c, I) => combine(I(0), I(1), c.P('mode', 'over'), c.P('opacity', 1));
  NODES.Repeat = (n, c, I) => {
    const L0 = I(0); const N = c.N; if (!L0) return empty(N); const P = c.P, count = Math.max(1, Math.round(P('count', 6))), pxp = P('px', .5) * N, pyp = P('py', .5) * N, a0 = P('angle0', 0) * DEG, ast = P('angleStep', 60) * DEG, centered = P('centered', false), dx = P('dx', 0), dy = P('dy', 0), scSt = P('scaleStep', 0), fdSt = P('fadeStep', 0), delay = P('delay', 0), mode = P('mode', 'add'), posX = P('posX', -1), posY = P('posY', -1), sc0 = P('scale0', 1), rotMin = P('rotMin', 0) * DEG, rotMax = P('rotMax', 0) * DEG, seed = Math.round(P('seed', 1)), layout = P('layout', 'step'), gsx = P('sx', 1), gsy = P('sy', 1), jit = P('jitter', 0), sc1 = P('scale1', 1), scPow = P('scalePow', 1), distP = P('dist', 1), B = [0, 1, 2, 3].map(k => [P('bx' + k, [.5, .5, .5, .5][k]), P('by' + k, [.2, .4, .6, .8][k])]);
    const r = rng(seed * 331 + 5); let acc = null; for (let i = 0; i < count; i++) { const f2 = c.f - Math.round(delay * i); if (f2 < 0) { r(); r(); continue; } const L = f2 === c.f ? L0 : I(0, f2); if (!L) continue; const k = count > 1 ? i / (count - 1) : 0; let ang = a0 + ast * (centered ? i - (count - 1) / 2 : i) + lerp(rotMin, rotMax, r()), sc = layout === 'bezier' ? lerp(sc0, sc1, Math.pow(k, scPow)) : sc0 * (1 - scSt * k), tx = dx * i, ty = dy * i; sc *= 1 + (r() * 2 - 1) * jit; if (layout === 'bezier') { const t = Math.pow(k, distP), u = 1 - t, bx = u * u * u * B[0][0] + 3 * u * u * t * B[1][0] + 3 * u * t * t * B[2][0] + t * t * t * B[3][0], by = u * u * u * B[0][1] + 3 * u * u * t * B[1][1] + 3 * u * t * t * B[2][1] + t * t * t * B[3][1]; tx = bx * N - pxp; ty = by * N - pyp; } else if (posX >= 0 || posY >= 0) { tx += (posX >= 0 ? posX * N - pxp : 0); ty += (posY >= 0 ? posY * N - pyp : 0); }
      const cs = Math.cos(-ang), sn = Math.sin(-ang), ssx = sc * gsx || .0001, ssy = sc * gsy || .0001; let T = warp(L, (x, y, s) => { const ddx = x - pxp - tx, ddy = y - pyp - ty, rx = ddx * cs - ddy * sn, ry = ddx * sn + ddy * cs; s[0] = pxp + rx / ssx; s[1] = pyp + ry / ssy; }); const fade = 1 - fdSt * k; if (fade < 1) { if (T.t === 'i') for (let q = 0; q < T.d.length; q++) T.d[q] *= fade; else for (let q = 3; q < T.d.length; q += 4) T.d[q] *= fade; } acc = acc ? combine(acc, T, mode === 'over' ? 'over' : mode, 1) : T; } return acc || empty(N);
  };
  NODES.Echo = (n, c, I) => {
    const L0 = I(0); if (!L0) return empty(c.N); const P = c.P, copies = Math.round(P('copies', 3)), step = Math.round(P('step', 1)), decay = P('decay', .6); let acc = L0; for (let i = 1; i <= copies; i++) { const f2 = c.f - i * step; if (f2 < 0) break; const L = I(0, f2); if (!L) break; const k = Math.pow(decay, i), S = L.t === 'i' ? (() => { const t = newI(L.w); for (let q = 0; q < t.d.length; q++) t.d[q] = L.d[q] * k; return t; })() : (() => { const t = newC(L.w); t.d.set(L.d); for (let q = 3; q < t.d.length; q += 4) t.d[q] *= k; return t; })(); acc = combine(S, acc, acc.t === 'i' ? 'max' : 'over', 1); } return acc;
  };
  NODES.Blur = (n, c, I) => { const L = I(0); return L ? blurLayer(L, Math.round(c.P('radius', 1)), Math.round(c.P('passes', 2))) : empty(c.N); };
  NODES.Glow = (n, c, I) => { const L = I(0); if (!L) return empty(c.N); const b = blurLayer(L, Math.round(c.P('radius', 2)), 2), s = c.P('strength', 1); if (L.t === 'i') { const o = newI(L.w); for (let i = 0; i < o.d.length; i++) o.d[i] = clamp(Math.max(L.d[i], L.d[i] + b.d[i] * s), 0, 1); return o; } const o = newC(L.w); for (let i = 0; i < L.w * L.w; i++) { const j = i * 4, a1 = L.d[j + 3], a2 = Math.min(1, b.d[j + 3] * s), a = Math.min(1, a1 + a2 * (1 - a1)); if (a > 1e-6) { for (let k = 0; k < 3; k++) o.d[j + k] = (L.d[j + k] * a1 + b.d[j + k] * a2 * (1 - a1)) / (a1 + a2 * (1 - a1) || 1); o.d[j + 3] = a; } } return o; };
  NODES.Levels = (n, c, I) => { let L = I(0); if (!L) return empty(c.N); L = toI(L); const P = c.P, lo = P('lo', 0), hi = P('hi', 1), g = P('gamma', 1), st = Math.round(P('steps', 0)), o = newI(L.w); for (let i = 0; i < o.d.length; i++) { let v = clamp((L.d[i] - lo) / Math.max(1e-6, hi - lo), 0, 1); v = Math.pow(v, 1 / g); if (st > 0) v = Math.round(v * st) / st; o.d[i] = v; } return o; };
  const BAYER4 = [0, 8, 2, 10, 12, 4, 14, 6, 3, 11, 1, 9, 15, 7, 13, 5], BAYER2 = [0, 2, 3, 1];
  NODES.Dither = (n, c, I) => { let L = I(0); if (!L) return empty(c.N); L = toI(L); const P = c.P, lv = Math.max(2, Math.round(P('levels', 4))), pat = P('pattern', 'bayer4'), st = P('strength', 1), N = L.w, o = newI(N), m = pat === 'bayer2' ? BAYER2 : BAYER4, ms = pat === 'bayer2' ? 2 : 4; for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) { const th = (m[(y % ms) * ms + (x % ms)] + .5) / (ms * ms), t = .5 + (th - .5) * st; o.d[y * N + x] = Math.floor(L.d[y * N + x] * (lv - 1) + t) / (lv - 1); } return o; };
  NODES.Displace = (n, c, I) => { const L = I(0); if (!L) return empty(c.N); const M = I(1) ? toI(I(1)) : null; if (!M) return L; const P = c.P, N = c.N, mode = P('mode', 'dir'), amt = P('amount', 4), ang = P('angle', 90) * DEG, cen = P('center', .5), cx = P('cx', .5) * N, cy = P('cy', .5) * N; return warp(L, (x, y, s) => { const m = (sampleI(M, x, y) - cen) * amt; let ox, oy; if (mode === 'radial') { const dx = x - cx, dy = y - cy, l = Math.hypot(dx, dy) || 1; ox = dx / l * m; oy = dy / l * m; } else if (mode === 'swirl') { const dx = x - cx, dy = y - cy, l = Math.hypot(dx, dy) || 1; ox = -dy / l * m; oy = dx / l * m; } else { ox = Math.cos(ang) * m; oy = Math.sin(ang) * m; } s[0] = x - ox; s[1] = y - oy; }); };
  NODES.Polar = (n, c, I) => { const L = I(0); if (!L) return empty(c.N); const P = c.P, N = c.N, rIn = P('rIn', 4), rOut = Math.max(rIn + .1, P('rOut', 30)), spin = P('spin', 0) * DEG, cx = P('cx', .5) * N, cy = P('cy', .5) * N, inv = P('invert', true); return warp(L, (x, y, s) => { const dx = x - cx, dy = y - cy, r = Math.hypot(dx, dy); if (r < rIn || r > rOut) return false; let u = (Math.atan2(dy, dx) - spin) / TAU; u = u - Math.floor(u); let v = (r - rIn) / (rOut - rIn); if (inv) v = 1 - v; s[0] = u * N; s[1] = v * N; }); };
  NODES.Pixelate = (n, c, I) => { const L = I(0); if (!L) return empty(c.N); const b = Math.max(1, Math.round(c.P('block', 2))), N = L.w, ch = L.t === 'i' ? 1 : 4, o = L.t === 'i' ? newI(N) : newC(N); for (let by = 0; by < N; by += b) for (let bx = 0; bx < N; bx += b) { const acc = new Float32Array(ch); let cnt = 0, asum = 0; for (let y = by; y < Math.min(N, by + b); y++) for (let x = bx; x < Math.min(N, bx + b); x++) { const i = (y * N + x) * ch; if (ch === 1) acc[0] += L.d[i]; else { const a = L.d[i + 3]; acc[0] += L.d[i] * a; acc[1] += L.d[i + 1] * a; acc[2] += L.d[i + 2] * a; asum += a; } cnt++; } for (let y = by; y < Math.min(N, by + b); y++) for (let x = bx; x < Math.min(N, bx + b); x++) { const i = (y * N + x) * ch; if (ch === 1) o.d[i] = acc[0] / cnt; else if (asum > 1e-6) { o.d[i] = acc[0] / asum; o.d[i + 1] = acc[1] / asum; o.d[i + 2] = acc[2] / asum; o.d[i + 3] = asum / cnt; } } } return o; };
  NODES.Mask = (n, c, I) => { const L = I(0), M0 = I(1); if (!L) return empty(c.N); if (!M0) return L; const M = toI(M0), P = c.P, mode = P('mode', 'multiply'), st = P('strength', 1), o = L.t === 'i' ? newI(L.w) : newC(L.w), fac = i => mode === 'cutout' ? 1 - st * M.d[i] : 1 - st + st * M.d[i]; if (L.t === 'i') for (let i = 0; i < o.d.length; i++) o.d[i] = L.d[i] * fac(i); else for (let i = 0; i < L.w * L.w; i++) { for (let k = 0; k < 3; k++) o.d[i * 4 + k] = L.d[i * 4 + k]; o.d[i * 4 + 3] = L.d[i * 4 + 3] * fac(i); } return o; };
  NODES.Palette = (n, c, I) => {
    const L = I(0); if (!L) return empty(c.N); const P = c.P, cols = (n.params && n.params.colors || ['#4a0d12', '#a3231b', '#e8591c', '#ffb030', '#fff1b8']).map(hexRgb), cut = P('cutoff', .1), shift = P('shift', 0), mode = P('mode', 'bands'), key = P('key', 'alpha'), op = P('opacity', 1), N = L.w, o = newC(N), k = cols.length;
    for (let i = 0; i < N * N; i++) { let v = L.t === 'i' ? L.d[i] : (key === 'luma' ? lumaOf(L.d[i * 4], L.d[i * 4 + 1], L.d[i * 4 + 2]) * L.d[i * 4 + 3] : L.d[i * 4 + 3]); if (v <= cut) continue; let w = clamp((v - cut) / Math.max(1e-6, 1 - cut) + shift, 0, 1), col; if (mode === 'smooth') { const q = w * (k - 1), i0 = Math.floor(q), i1 = Math.min(k - 1, i0 + 1), tt = q - i0; col = [0, 1, 2].map(m => lerp(cols[i0][m], cols[i1][m], tt)); } else col = cols[Math.min(k - 1, Math.floor(w * k))]; o.d[i * 4] = col[0]; o.d[i * 4 + 1] = col[1]; o.d[i * 4 + 2] = col[2]; o.d[i * 4 + 3] = op; } return o;
  };
  NODES.Tint = (n, c, I) => { let L = I(0); if (!L) return empty(c.N); L = toC(L); const M = I(1) ? toI(I(1)) : null, P = c.P, col = hexRgb(P('color', '#ffffff')), am = P('amount', 1), br = P('bright', 1), op = P('opacity', 1), N = L.w, o = newC(N); for (let i = 0; i < N * N; i++) { const j = i * 4, m = M ? M.d[i] : 1, a = lerp(L.d[j + 3], L.d[j + 3] * op, m) , mix = am * m; o.d[j + 3] = a; for (let k = 0; k < 3; k++) o.d[j + k] = clamp(lerp(L.d[j + k], col[k], mix) * lerp(1, br, m), 0, 1); } return o; };
  NODES.Outline = (n, c, I) => { let L = I(0); if (!L) return empty(c.N); L = toC(L); const M = I(1) ? toI(I(1)) : null, P = c.P, col = hexRgb(P('color', '#10142e')), th = P('threshold', .5), w = Math.round(P('width', 1)), corners = P('corners', false), mode = P('mode', 'outer'), N = L.w, o = newC(N); o.d.set(L.d); const solid = (x, y) => x >= 0 && y >= 0 && x < N && y < N && L.d[(y * N + x) * 4 + 3] >= th; const nb = []; for (let dy = -w; dy <= w; dy++) for (let dx = -w; dx <= w; dx++) { if (!dx && !dy) continue; if (!corners && dx && dy) continue; nb.push([dx, dy]); }
    for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) { if (M && M.d[y * N + x] < .5) continue; const s = solid(x, y); let edge = false; if (mode === 'outer' ? !s : s) for (const [dx, dy] of nb) if (mode === 'outer' ? solid(x + dx, y + dy) : !solid(x + dx, y + dy)) { edge = true; break; } if (edge) { const j = (y * N + x) * 4; o.d[j] = col[0]; o.d[j + 1] = col[1]; o.d[j + 2] = col[2]; o.d[j + 3] = 1; } } return o; };
  NODES.Quantize = (n, c, I) => { let L = I(0); if (!L) return empty(c.N); L = toC(L); const P = c.P, pal = (n.params && n.params.colors || []).map(hexRgb), hard = P('alpha', 'keep') === 'hard', th = P('threshold', .5), N = L.w, o = newC(N); if (!pal.length) return L; for (let i = 0; i < N * N; i++) { const j = i * 4; let best = 0, bd = 9; for (let q = 0; q < pal.length; q++) { const d = (pal[q][0] - L.d[j]) ** 2 + (pal[q][1] - L.d[j + 1]) ** 2 + (pal[q][2] - L.d[j + 2]) ** 2; if (d < bd) { bd = d; best = q; } } o.d[j] = pal[best][0]; o.d[j + 1] = pal[best][1]; o.d[j + 2] = pal[best][2]; o.d[j + 3] = hard ? (L.d[j + 3] >= th ? 1 : 0) : L.d[j + 3]; } return o; };
  NODES.Output = (n, c, I) => I(0) || empty(c.N);

  /* ---------- 그래프 실행 ---------- */
  function compile(g) {
    const byId = new Map(), ins = new Map(); g.nodes.forEach(n => { byId.set(n.id, n); ins.set(n.id, []); }); g.links.forEach(l => { const a = ins.get(l.t); if (a) a[l.p] = l.f; });
    const outs = g.nodes.filter(n => n.type === 'Output'); if (outs.length !== 1) throw new Error('Output 노드는 정확히 하나여야 한다');
    return { byId, ins, out: outs[0], s: g.settings };
  }
  function renderFrame(cg, f, warnings, K) {
    const s = cg.s, N = s.size * K, F = s.frames, memo = new Map();
    const ev = (id, ff) => {
      const key = id + '@' + ff; if (memo.has(key)) return memo.get(key);
      const n = cg.byId.get(id); if (!n) return null; const impl = NODES[n.type];
      const tl = ff / F, tN = s.loop ? ff / F : (F > 1 ? ff / (F - 1) : 0);
      const pxl = PX[n.type] || [], pint = PXINT[n.type] || [], ctx = { N, k: K, f: ff, frames: F, loop: !!s.loop, t: tN, tl, P: (name, def) => { let v = pv(n.params && n.params[name], def, ff, tN); if (K !== 1 && typeof v === 'number' && pxl.indexOf(name) >= 0) { v *= K; if (pint.indexOf(name) >= 0) v = Math.max(v > 0 ? 1 : 0, Math.round(v)); } return v; } };
      const srcs = cg.ins.get(id); let r;
      if (!impl) { if (warnings.indexOf(n.type) < 0) warnings.push(n.type); r = empty(N); } else r = impl(n, ctx, (port, f2) => { const sid = srcs[port]; return sid === undefined ? null : ev(sid, f2 === undefined ? ff : f2); });
      memo.set(key, r); return r;
    };
    return ev(cg.out.id, f);
  }
  function finish(L, N, outNode) {
    const P = outNode.params || {}, hard = (P.alpha || 'hard') === 'hard', th = P.threshold === undefined ? .5 : P.threshold, C = toC(L), px = new Uint8ClampedArray(N * N * 4);
    for (let i = 0; i < N * N; i++) { const j = i * 4; let a = C.d[j + 3]; if (hard) a = a >= th ? 1 : 0; px[j] = Math.round(C.d[j] * 255); px[j + 1] = Math.round(C.d[j + 1] * 255); px[j + 2] = Math.round(C.d[j + 2] * 255); px[j + 3] = Math.round(clamp(a, 0, 1) * 255); } return px;
  }
  function render(graph, opts) {
    const K = Math.max(1, Math.round((opts && opts.scale) || 1)), cg = compile(graph), s = cg.s, warnings = [], data = []; for (let f = 0; f < s.frames; f++) data.push(finish(renderFrame(cg, f, warnings, K), s.size * K, cg.out));
    return { size: s.size * K, baseSize: s.size, scale: K, frames: s.frames, fps: s.fps, loop: !!s.loop, data, warnings };
  }
  function strip(res, doc) { /* 브라우저: 프레임을 가로 스트립 캔버스로 */ const cv = (doc || document).createElement('canvas'); cv.width = res.size * res.frames; cv.height = res.size; const g = cv.getContext('2d'); res.data.forEach((px, f) => g.putImageData(new ImageData(px, res.size, res.size), f * res.size, 0)); return cv; }
  const api = { render, strip, NODES: Object.keys(NODES), EASE };
  if (typeof module !== 'undefined' && module.exports) module.exports = api; else root.FXGraph = api;
})(typeof window !== 'undefined' ? window : globalThis);
